import { createContext, useMemo, useState } from "react";

const translations = {
  en: {
    appName: "SUNIL KHAD BEEJ BHANDER",
    smartAgriculture: "Smart Agriculture",
    cropCareLine: "Crop care and shop management in one place.",
    shopkeeperDashboard: "Shopkeeper Dashboard",
    farmerDashboard: "Farmer Dashboard",
    rewardPoints: "reward points",
    logout: "Logout",
    overview: "Overview",
    products: "Products",
    orders: "Orders",
    chat: "Chat",
    cropUploads: "Crop Uploads",
    shop: "Shop",
    cart: "Cart",
    aiUpload: "AI Upload",
    welcomeBack: "Welcome back",
    loginToAccount: "Login to your account",
    email: "Email",
    password: "Password",
    login: "Login",
    signingIn: "Signing in...",
    noAccount: "No account yet?",
    registerHere: "Register here",
    demoAdmin: "Demo admin",
    demoClient: "Demo client",
    heroTitle: "Fertilizer, pesticide and crop support in one smart dashboard.",
    heroText:
      "Farmers can shop, chat, upload crop images, and track rewards while the shopkeeper manages products, orders, and field support.",
    createAccount: "Create account",
    joinApp: "Join SUNIL KHAD BEEJ BHANDER",
    fullName: "Full name",
    clientFarmer: "Client / Farmer",
    adminShopkeeper: "Admin / Shopkeeper",
    adminInviteCode: "Admin invite code",
    creating: "Creating...",
    alreadyAccount: "Already have an account?",
    searchProducts: "Search products",
    allCategories: "All categories",
    pesticides: "Pesticides",
    fertilizers: "Fertilizers",
    supplements: "Supplements",
    tools: "Tools",
    seeds: "Seeds",
    stock: "Stock",
    addToCart: "Add to cart",
    viewDetails: "View details",
    productDetails: "Product details",
    close: "Close",
    category: "Category",
    availableStock: "Available stock",
    productTags: "Product tags",
    noTags: "No tags added",
    recommendedFor: "Recommended for",
    productInfoText:
      "Use this product based on crop stage, field condition, and label guidance from the shopkeeper.",
    yourCart: "Your cart",
    checkout: "Checkout",
    enterDeliveryAddress: "Enter delivery address",
    orderNotes: "Order notes",
    total: "Total",
    placeOrder: "Place order",
    welcome: "Welcome",
    overviewText:
      "Track your reward points, review crop scans, order products, and stay connected with the shopkeeper.",
    recentOrders: "Recent Orders",
    recentScans: "Recent Scans",
    badges: "Badges",
    rewardHistory: "Reward History",
    unlockBadges: "Keep shopping and uploading scans to unlock badges.",
    order: "Order",
    language: "Language",
    english: "English",
    hindi: "Hindi",
    productName: "Product name",
    price: "Price",
    tagsComma: "Tags, comma separated",
    description: "Description",
    addProduct: "Add product",
    updateProduct: "Update product",
    cancelEdit: "Cancel edit",
    editProduct: "Edit product",
    deleteProduct: "Delete product",
    productAdded: "Product added",
    productUpdated: "Product updated",
    productRemoved: "Product removed",
    totalClients: "Total Clients",
    sales: "Sales",
    recentRewardActivity: "Recent Reward Activity",
    clientRewardBoard: "Client Reward Board",
    grantBonusReward: "Grant Bonus Reward",
    grantBonus: "Grant bonus",
    bonusGranted: "Bonus reward granted",
    allClientsRewarded: "All listed clients have already received bonus",
    loadingAnalytics: "Loading analytics...",
    contacts: "Contacts",
    pickContact: "Pick a contact",
    typeMessage: "Type your message",
    loadContactsError: "Unable to load chat contacts",
    loadMessagesError: "Unable to load messages",
    liveChatError: "Live chat connection failed. Messages may need a refresh.",
    selectContactMessage: "Select a contact and type a message",
    sendMessageError: "Unable to send message",
    uploadCropImage: "Upload crop image",
    imagePreview: "Image preview",
    analyzing: "Analyzing...",
    detectDisease: "Detect disease",
    aiResult: "AI Result",
    confidence: "Confidence",
    suggestedTreatment: "Suggested treatment",
    improveScan: "How to improve the scan",
    uploadHint: "Upload a clear crop or leaf image to get the AI-assisted disease screening result.",
    scanCompleted: "Scan completed",
    loadAdminScansError: "Unable to load crop scans",
    loadOrdersError: "Unable to load orders",
    orderStatusUpdated: "Order status updated",
    loadAdminDataError: "Unable to load dashboard analytics"
    ,
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    certificates: "Certificates",
    feedback: "Feedback",
    feedbackContact: "Feedback & Contact",
    contactUs: "Contact us",
    contactInformation: "Shop Contact Information",
    contactInformationText: "Use these details to call, visit, or email the shop directly.",
    shopLocation: "Shop location",
    phoneNumber: "Phone number",
    emailAddress: "Email address",
    feedbackContactTitle: "Send feedback or message",
    feedbackContactSubtitle: "Share your review or send a message to the shopkeeper from here.",
    yourName: "Your name",
    yourEmail: "Your email",
    phoneNumberPlaceholder: "Phone number",
    subjectPlaceholder: "Subject",
    messagePlaceholder: "Write your feedback or message",
    ratingLabel: "Rating",
    messageSent: "Message sent",
    feedbackSubmitted: "Feedback submitted",
    submitFeedback: "Submit feedback",
    publicReviews: "Public Reviews",
    yourMessagesRatings: "Your Messages & Ratings",
    noPublicReviews: "No public reviews yet.",
    noMessagesYet: "You have not submitted any message or feedback yet.",
    generalFeedback: "General feedback",
    generalMessage: "General message",
    reviewed: "Reviewed",
    newStatus: "New",
    certificatesSubtitle: "See the certificates and trust marks earned by the shopkeeper.",
    issuedOn: "Issued on",
    viewCertificate: "View certificate",
    certificatePreview: "Certificate image",
    openFullImage: "Open full image",
    certificateDescriptionFallback: "Certificate details will appear here.",
    noOrdersYet: "You have not placed any order yet.",
    noOrdersYetText: "Browse products from the shop and place your first order to see your order history here."
  },
  hi: {
    appName: "SUNIL KHAD BEEJ BHANDER",
    smartAgriculture: "स्मार्ट एग्रीकल्चर",
    cropCareLine: "फसल देखभाल और दुकान प्रबंधन एक ही जगह।",
    shopkeeperDashboard: "दुकानदार डैशबोर्ड",
    farmerDashboard: "किसान डैशबोर्ड",
    rewardPoints: "रिवॉर्ड पॉइंट्स",
    logout: "लॉगआउट",
    overview: "ओवरव्यू",
    products: "प्रोडक्ट्स",
    orders: "ऑर्डर्स",
    chat: "चैट",
    cropUploads: "फसल अपलोड",
    shop: "दुकान",
    cart: "कार्ट",
    aiUpload: "एआई अपलोड",
    welcomeBack: "वापसी पर स्वागत है",
    loginToAccount: "अपने अकाउंट में लॉगिन करें",
    email: "ईमेल",
    password: "पासवर्ड",
    login: "लॉगिन",
    signingIn: "लॉगिन हो रहा है...",
    noAccount: "अभी अकाउंट नहीं है?",
    registerHere: "यहाँ रजिस्टर करें",
    demoAdmin: "डेमो एडमिन",
    demoClient: "डेमो क्लाइंट",
    heroTitle: "खाद, कीटनाशक और फसल सहायता एक स्मार्ट डैशबोर्ड में।",
    heroText:
      "किसान खरीदारी, चैट, फसल इमेज अपलोड और रिवॉर्ड ट्रैक कर सकते हैं, जबकि दुकानदार प्रोडक्ट, ऑर्डर और सपोर्ट संभालता है।",
    createAccount: "अकाउंट बनाएं",
    joinApp: "SUNIL KHAD BEEJ BHANDER से जुड़ें",
    fullName: "पूरा नाम",
    clientFarmer: "क्लाइंट / किसान",
    adminShopkeeper: "एडमिन / दुकानदार",
    adminInviteCode: "एडमिन इनवाइट कोड",
    creating: "बनाया जा रहा है...",
    alreadyAccount: "क्या पहले से अकाउंट है?",
    searchProducts: "प्रोडक्ट खोजें",
    allCategories: "सभी कैटेगरी",
    pesticides: "कीटनाशक",
    fertilizers: "उर्वरक",
    supplements: "सप्लीमेंट्स",
    tools: "टूल्स",
    seeds: "बीज",
    stock: "स्टॉक",
    addToCart: "कार्ट में जोड़ें",
    viewDetails: "विवरण देखें",
    productDetails: "प्रोडक्ट विवरण",
    close: "बंद करें",
    category: "कैटेगरी",
    availableStock: "उपलब्ध स्टॉक",
    productTags: "प्रोडक्ट टैग्स",
    noTags: "कोई टैग नहीं जोड़ा गया",
    recommendedFor: "उपयुक्त उपयोग",
    productInfoText:
      "इस प्रोडक्ट का उपयोग फसल की अवस्था, खेत की स्थिति और दुकानदार के निर्देश के अनुसार करें।",
    yourCart: "आपका कार्ट",
    checkout: "चेकआउट",
    enterDeliveryAddress: "डिलीवरी पता दर्ज करें",
    orderNotes: "ऑर्डर नोट्स",
    total: "कुल",
    placeOrder: "ऑर्डर करें",
    welcome: "स्वागत है",
    overviewText:
      "अपने रिवॉर्ड पॉइंट्स, फसल स्कैन, ऑर्डर और दुकानदार के साथ संपर्क को एक जगह ट्रैक करें।",
    recentOrders: "हाल के ऑर्डर",
    recentScans: "हाल के स्कैन",
    badges: "बैज",
    rewardHistory: "रिवॉर्ड हिस्ट्री",
    unlockBadges: "बैज पाने के लिए खरीदारी और स्कैन अपलोड करते रहें।",
    order: "ऑर्डर",
    language: "भाषा",
    english: "अंग्रेज़ी",
    hindi: "हिंदी",
    productName: "प्रोडक्ट नाम",
    price: "कीमत",
    tagsComma: "टैग्स, कॉमा से अलग करें",
    description: "विवरण",
    addProduct: "प्रोडक्ट जोड़ें",
    updateProduct: "प्रोडक्ट अपडेट करें",
    cancelEdit: "एडिट रद्द करें",
    editProduct: "प्रोडक्ट एडिट करें",
    deleteProduct: "प्रोडक्ट हटाएँ",
    productAdded: "प्रोडक्ट जोड़ दिया गया",
    productUpdated: "प्रोडक्ट अपडेट हो गया",
    productRemoved: "प्रोडक्ट हटा दिया गया",
    totalClients: "कुल क्लाइंट्स",
    sales: "बिक्री",
    recentRewardActivity: "हाल की रिवॉर्ड गतिविधि",
    clientRewardBoard: "क्लाइंट रिवॉर्ड बोर्ड",
    grantBonusReward: "बोनस रिवॉर्ड दें",
    grantBonus: "बोनस दें",
    bonusGranted: "बोनस रिवॉर्ड दे दिया गया",
    loadingAnalytics: "एनालिटिक्स लोड हो रहा है...",
    contacts: "संपर्क",
    pickContact: "कोई संपर्क चुनें",
    typeMessage: "अपना संदेश लिखें",
    loadContactsError: "चैट संपर्क लोड नहीं हो सके",
    loadMessagesError: "मैसेज लोड नहीं हो सके",
    liveChatError: "लाइव चैट कनेक्शन विफल हुआ। रिफ्रेश की जरूरत पड़ सकती है।",
    selectContactMessage: "एक संपर्क चुनें और संदेश लिखें",
    sendMessageError: "संदेश भेजा नहीं जा सका",
    uploadCropImage: "फसल की इमेज अपलोड करें",
    imagePreview: "इमेज प्रीव्यू",
    analyzing: "विश्लेषण हो रहा है...",
    detectDisease: "रोग पहचानें",
    aiResult: "एआई परिणाम",
    confidence: "विश्वास स्तर",
    suggestedTreatment: "सुझाया गया उपचार",
    improveScan: "स्कैन बेहतर कैसे करें",
    uploadHint: "एआई-आधारित परिणाम पाने के लिए फसल या पत्ती की साफ तस्वीर अपलोड करें।",
    scanCompleted: "स्कैन पूरा हुआ",
    loadAdminScansError: "फसल स्कैन लोड नहीं हो सके",
    loadOrdersError: "ऑर्डर लोड नहीं हो सके",
    orderStatusUpdated: "ऑर्डर स्टेटस अपडेट हो गया",
    loadAdminDataError: "डैशबोर्ड एनालिटिक्स लोड नहीं हो सके"
    ,
    theme: "थीम",
    light: "लाइट",
    dark: "डार्क"
  }
};

Object.assign(translations.hi, {
  certificates: "Praman Patra",
  feedback: "Pratikriya",
  feedbackContact: "Pratikriya aur Sampark",
  contactUs: "Sampark karein",
  contactInformation: "Dukaan ki sampark jankari",
  contactInformationText: "Yahan se aap seedha dukaan ko call, visit ya email kar sakte hain.",
  shopLocation: "Dukaan ka pata",
  phoneNumber: "Phone number",
  emailAddress: "Email pata",
  feedbackContactTitle: "Pratikriya ya sandesh bhejein",
  feedbackContactSubtitle: "Yahan se apna review dein ya shopkeeper ko message bhejein.",
  yourName: "Aapka naam",
  yourEmail: "Aapka email",
  phoneNumberPlaceholder: "Phone number",
  subjectPlaceholder: "Vishay",
  messagePlaceholder: "Apna feedback ya sandesh likhein",
  ratingLabel: "Rating",
  messageSent: "Sandesh bhej diya gaya",
  feedbackSubmitted: "Pratikriya bhej di gayi",
  submitFeedback: "Pratikriya bhejein",
  publicReviews: "Sabhi ke liye reviews",
  yourMessagesRatings: "Aapke message aur ratings",
  noPublicReviews: "Abhi tak koi public review nahi hai.",
  noMessagesYet: "Aapne abhi tak koi message ya feedback submit nahi kiya hai.",
  generalFeedback: "Samanya pratikriya",
  generalMessage: "Samanya sandesh",
  reviewed: "Review ho chuka hai",
  newStatus: "Naya",
  certificatesSubtitle: "Dukaan ko mile certificate aur bharose ki jankari dekhein.",
  issuedOn: "Jari ki tarikh",
  viewCertificate: "Certificate dekhein",
  certificatePreview: "Certificate image",
  openFullImage: "Puri image kholein",
  certificateDescriptionFallback: "Certificate ki jankari yahan dikhai jayegi.",
  noOrdersYet: "Aapne abhi tak koi order nahi kiya hai.",
  noOrdersYetText: "Dukaan ke products dekhein aur apna pehla order karein. Order history yahin dikhai degi."
});

Object.assign(translations.hi, {
  allClientsRewarded: "Sabhi clients ko bonus mil chuka hai."
});

export const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem("agro-language") || "en");

  const changeLanguage = (nextLanguage) => {
    setLanguage(nextLanguage);
    localStorage.setItem("agro-language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: changeLanguage,
      t: (key) => translations[language]?.[key] || translations.en[key] || key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
